baseURL = 'https://me.djh1960.uk'
languageCode = 'en-gb'
title = 'David John Hulatt'
theme = "m10c"
[params]
author = 'David John Hulatt'
description = 'Home for djh1960.uk'
avatar = 'avatar.jpg'
menu_item_separator = '-'
favicon = '/static/flavicon.ico'
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
[[params.social]]
icon = "github"
name = "My Github"
url = "https://github.com/vaga"
[params.style]
darkestColor = "#20B2AA"
darkColor = "#212121"
lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#ffffff"
