baseURL = 'https://djh1960.website'
languageCode = 'en-gb'
title = 'David John Hulat: Hello there.'
theme = "m10c"
[params]
author = 'David John Hulatt'
description = 'Home for djh1960.uk'
avatar = ''
menu_item_separator = '-'
favicon = ''
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
[[params.social]]
icon = "github"
name = "My Github"
url = "https://github.com/vaga"
[params.style]
darkestColor = "#d35050"
darkColor = "#212121"
lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#ffffff"
