baseURL = 'https://me.djh1960.uk'
languageCode = 'en-gb'
title = 'David John Hulatt'
theme = "m10c"
[params]
author = 'David John Hulatt'
description = 'Home for djh1960.uk'
avatar = 'avatar.jpg'
favicon = '/skull.ico'
menu_item_separator = '-'
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 4
[[params.social]]
icon = "github"
name = "My Github"
url = "https://github.com/davidjohn1960"
[[params.social]]
icon = "email"
name = "My Email Address"
url = "mailto:me@djh1960.uk"
[params.style]
darkestColor = "#20B2AA"
darkColor = "#212121"
lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#ffffff"
